<?php

/**
 * @file
 * Contains search_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function search_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_log module.
    case 'help.page.search_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('maintains search history') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function search_log_theme() {
  return [
    'search_log' => [
      'render element' => 'children',
    ],
  ];
}

function search_log_search_preprocess($text, $langcode = NULL){

 if (!isset($langcode)) {
  $langcode = \Drupal::languageManager()
  ->getCurrentLanguage()
  ->getId();

// print_r($langcode);
// die();
}

if($searchterm=(db_query('SELECT searchterm From {search_log}'))){
  db_update('search_log')
  ->expression('counter','counter + 1')
  ->execute();
}
else
{
  db_insert('search_log')->fields(array('language'=>$langcode,
    'searchterm'=>$text,''))->execute();
  drupal_set_message(t($text));
}

}
