<?php

/**
 * @file
 * Contains search_log.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function search_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_log module.
    case 'help.page.search_log':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('maintains search history') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function search_log_theme() {
  return [
    'search_log' => [
      'render element' => 'children',
    ],
  ];
}
